# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Tales From a New Dad
tagline:             'I have no idea what I''m doing.'
description:         'I''m a first time father to an infant daughter. I''ve read a few books on how to do this father thing, but I''m likely wildly unprepared. I post about my experiences and sometimes said things are funny.'
url:                 http://blog.talesfromanewdad.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jay
  url:               http://talesfromanewdad.com
  email:             talesfromanewdad@gmail.com

# Custom vars
version:             1.0.0
gems:               [jekyll-paginate]

excerpt_separator:  <!--more-->
markdown: kramdown
