# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tales From a New Dad
email: talesfromanewdad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a first time father documenting the daily occurrences of having a pregnant wife and young step daughter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://talesfromanewdad.com" # the base hostname & protocol for your site
twitter_username: talesfromanewdad

# Build settings
markdown: kramdown
paginate: 5

kramdown:
  syntax_highlighting: rouge